{% load humfrey_sparql %}
CONSTRUCT {
  {{ url|uri }} foaf:topic ?uri .
  ?uri ?b ?c .
  ?c ?d ?e . 
} WHERE {
{% if type %}
  VALUES ?type {
{% for t in type %}
    {{ t|uri }}{% endfor %}
  }
{% else %}
  ?type rdfs:subClassOf* org:Organization .
{% endif %}
  ?uri a ?type .
  {% if oxpoints %}
  EXISTS { ?uri skos:notation ?notation . FILTER(DATATYPE(?notation) = oxnotation:oxpoints) }
  {% endif %}
  {
    ?uri ?b ?c
    FILTER (?b NOT IN (mlo:offers))
  } UNION {
    VALUES ?b { v:adr v:tel }
    ?uri ?b ?c . ?c ?d ?e
  }
}